[package]
name = "compile_proto"
version = "0.1.0"
authors = ["zhangtailin <zhangtailin@ziggurat.cn>"]
edition = "2018"

[dependencies]
protoc-grpcio = "1.0.2"
walkdir = "2.2.8"
protobuf = { version = "2.8", features = ["with-bytes"] }