[workspace]

members = [
    "node",
    "proto",
    "logger",
    "network",
    "config",
    "consensus",
    "common/compile_proto",
    "common/failure_ext",
    "common/crypto",
]

[profile.release]
debug = true