[package]
name = "proto"
version = "0.1.0"
authors = ["zhangtailin <zhangtailin@ziggurat.cn>"]
edition = "2018"

[dependencies]
protobuf = "2.7.0"
grpcio = "0.4.4"
futures = "0.1.28"

[build-dependencies]
compile_proto = { path = "../common/compile_proto" }