[package]
name = "node"
version = "0.1.0"
authors = ["zhangtailin <zhangtailin@ziggurat.cn>"]
edition = "2018"

[dependencies]
crossbeam = "0.7"
logger = { path = "../logger" }
network = { path = "../network" }
config = { path = "../config" }
consensus = { path = "../consensus" }